

laliga_detail='**La Liga**, officially known as LaLiga Santander for sponsorship reasons, is the top professional football division of the Spanish football league system. Administered by the Liga Nacional de Fútbol Profesional (LFP), it is contested by 20 teams, with the three lowest-placed teams relegated to the Segunda División and replaced by the top two teams in that division along with the winner of a play-off.La Liga was founded in 1929 by José María Acha, a director at Arenas Club de Getxo. The first season included ten teams, and Barcelona won the inaugural title. Since then, it has become one of the most popular professional sports leagues in the world, known for its competitive and high-quality football.'


bundesliga_detail='The **Bundesliga** is the premier professional football league in Germany and one of the top leagues in the world. Known for its high average attendance and competitive matches, it operates with 18 teams and follows a system of promotion and relegation with the 2. Bundesliga, the second division.The Bundesliga was founded in 1962 in Dortmund and the first season started in 1963. It was created to replace the regional league system in Germany, aiming to consolidate the best teams into a single national league.Each of the 18 teams in the Bundesliga plays 34 games per season, once at home and once away against every other team.'

ligue1_detail="**Ligue 1** is the top professional football league in France, operated by the Ligue de Football Professionnel. It represents the pinnacle of the French football league system and is one of Europe's major national leagues.Ligue 1 was established in 1932 under the name 'National' before changing to 'Division 1' after a year, and it adopted its current name, Ligue 1, in the 2002/2003 season.Ligue 1 continues to evolve and adapt, maintaining its status as one of the top football leagues in Europe, known for its competitive nature, unique fan culture, and ability to produce and attract top talent."

prem_detail='The **Premier League** is the top tier of English football and one of the most popular and competitive football leagues in the world. Established in 1992, it has grown to become a global cultural phenomenon, known for its high-paced action, deep-rooted traditions, and broad international viewership.The Premier League was formed in 1992 when clubs in the Football League First Division decided to break away from the Football League to take advantage of a lucrative television rights deal.The league consists of 20 clubs. Each team plays 38 matches during the season, facing each other team both at home and away.The Premier League has a massive global following, with games broadcast in 212 territories to 643 million homes and a potential TV audience of 4.7 billion people.'

serieA_detail="**Serie A** is the top professional football league in Italy and one of the premier football leagues in the world. Known for its tactical rigor, historical teams, and passionate fan bases, Serie A has been home to many of the world's greatest players and most decorated clubs.Serie A was officially formed in 1929, evolving from earlier competitions dating back to the 1890s. Since its inception, it has been the pinnacle of Italian football.The league consists of 20 clubs. Each season, these teams compete in a round-robin format, playing each other twice, home and away, totaling 38 matches each.In recent years, Serie A has faced financial difficulties, with several clubs facing economic challenges. However, renewed investment and management have begun to revive the league's stature."

ligue2_detail='**Ligue 2** is the second tier of professional football in France, sitting just below Ligue 1 in the hierarchy. It plays a crucial role in the French football league system, providing a platform for clubs to compete for promotion to the top flight, while also facing the threat of relegation to the Championnat National, the third tier.Ligue 2 clubs often operate under more stringent financial constraints than their Ligue 1 counterparts. This dynamic requires effective management both on and off the pitch to ensure competitiveness and financial health.'
